### PR TITLE
Adding EFLOW-Mariner specifc commands

### PR DESCRIPTION
**Pull request by fcabrera23**

### CODE REVIEW

**Comment by jlian** [comment]
We also need updates for `config.toml`, right?

**Comment by fcabrera23** [comment]
@jlian what do you mean by config.toml? This it's just for adding CA certs to the OS.

**Comment by jlian** [comment]
@fcabrera23 from here thanks @terrymandin

https://github.com/terrymandin/EFLOWNestedEdge/blob/main/README.md#step-1---create-the-device-installation-scripts 

image

We should also test this tool e2e with EFLOW before merging

**Comment by fcabrera23** [comment]
@jlian  this is not part of this script - That's part of the OS configuration. We plan to move that in our next EFLOW update, so that step will be no longer necessary.

**Comment by jlian** [comment]
I think as part of the releases there are templates that include these configs like this one https://github.com/Azure-Samples/iotedge_config_cli/blob/main/templates/tutorial/device_config.toml

So when customer runs 

```bash
./iotedge_config --config ~/nestedIotEdgeTutorial/iotedge_config_cli_release/templates/tutorial/iotedge_config.yaml --output ~/nestedIotEdgeTutorial/iotedge_config_cli_release/outputs -f
```

It consumes from the template `config.toml`

image

To update this for EFLOW, I'm actually not sure what is the best approach. We could just have a different template for EFLOW but ideally it's a bit smarter than that and can automatically fill the right config based on the OS. Or maybe we should just take this part out and update the system defaults, but @lfitchett I think said that wouldn't work.

Thoughts? CC @varunpuranik

**Comment by jlian** [comment]
After seeing a message from Paramesh looks like I misunderstood. Basically EFLOW 1.4 will have the same sockets as the default config.

**Comment by fcabrera23** [comment]
Hi @jlian,

We are introducing the change of the sockets in the EFLOW 1.3 version next week. So that step won't be necessary anymore. I think the PR should be fine now.

Thanks,
Francisco

**Comment by jlian** [comment]
Can we test your change with EFLOW 1.3 before merging?

**Comment by fcabrera23** [comment]
@jlian  - Yes, I'm creating the guide also and will test everything as soon as i have the new EFLOW 1.3 image.

**Comment by fcabrera23** [comment]
@jlian  - I just finished testing with the new EFLOW 1.3 version and suggested PR changes, plus the inbox sockets changes work correctly.

**Comment by jlian** [comment]
Great! I don't have ability to merge and I guess the `build` check needs to run. @lfitchett or @varunpuranik can you help?

**Comment by jlian** [comment]
BTW @fcabrera23 how feasible would it be to make this more EFLOW native with PowerShell commands instead of having to ask the user to go into the Linux parts?

**Review by lfitchett — APPROVED** [review]

**Pull request merged**
